/* LSPD RMS - Penal code data.
 * Extracted verbatim from the original penal calculator (fine in USD, jail in months). */
window.PENAL_DATA = {
    "1A": {"nama": "General Traffic Violations", "deskripsi": "Mengemudi di jalur salah, putar balik ilegal", "denda": 1000, "penjara": 0},
    "1B": {"nama": "Failed or Refuse to Pay Fine", "deskripsi": "Tidak dapat atau menolak membayar denda", "denda": 1500, "penjara": 5},
    "1C-A": {"nama": "No License - Kendaraan Umum", "deskripsi": "Mengemudi tanpa SIM", "denda": 1000, "penjara": 5},
    "1C-B": {"nama": "No License - Kapal Laut", "deskripsi": "Kapal tanpa izin", "denda": 2000, "penjara": 10},
    "1C-C": {"nama": "No License - Truk Ringan", "deskripsi": "Truk ringan tanpa lisensi", "denda": 2000, "penjara": 15},
    "1C-D": {"nama": "No License - Truk Berat", "deskripsi": "Truk berat tanpa lisensi", "denda": 3000, "penjara": 20},
    "1C-E": {"nama": "No License - Pesawat/Heli", "deskripsi": "Pesawat/helikopter tanpa izin", "denda": 4000, "penjara": 30},
    "1D": {"nama": "Reckless Driving", "deskripsi": "Mengemudi ugal-ugalan", "denda": 1000, "penjara": 0},
    "1E": {"nama": "Speeding", "deskripsi": "Melebihi batas kecepatan", "denda": 1000, "penjara": 0},
    "1F": {"nama": "Improper Parking", "deskripsi": "Parkir sembarangan", "denda": 1000, "penjara": 0},
    "1G": {"nama": "Illegal Modifications", "deskripsi": "Modifikasi ilegal", "denda": 1500, "penjara": 0},
    "1H": {"nama": "Unregistered Vehicles", "deskripsi": "Kendaraan tidak terdaftar", "denda": 1000, "penjara": 0},
    "1I": {"nama": "Vehicular Endangerment", "deskripsi": "Menabrak tanpa pertolongan", "denda": 2000, "penjara": 15},
    "1J": {"nama": "Vehicle Manslaughter", "deskripsi": "Membunuh dengan kendaraan", "denda": 4000, "penjara": 30},
    "1K": {"nama": "DWI or DUI", "deskripsi": "Mengemudi di bawah pengaruh", "denda": 2000, "penjara": 20},
    "1L": {"nama": "Illegal Street Racing", "deskripsi": "Balapan liar", "denda": 3000, "penjara": 20},
    "1M": {"nama": "Evading from LEO", "deskripsi": "Kabur dari petugas", "denda": 3000, "penjara": 20},
    "1N": {"nama": "Flight Regulations", "deskripsi": "Melanggar aturan terbang", "denda": 3000, "penjara": 0},
    "1O": {"nama": "Emergency Landing", "deskripsi": "Pendaratan darurat tanpa izin", "denda": 3000, "penjara": 0},
    "1P": {"nama": "Failure to Yield Emergency", "deskripsi": "Tidak beri jalan darurat", "denda": 1000, "penjara": 0},
    "1Q": {"nama": "Failure to Yield Roadblock", "deskripsi": "Menerobos roadblock", "denda": 2000, "penjara": 0},
    "1R": {"nama": "Following Emergency Vehicle", "deskripsi": "Mengikuti kendaraan darurat", "denda": 2000, "penjara": 0},
    "1S": {"nama": "Altering Vehicle ID", "deskripsi": "Mengubah nomor kendaraan", "denda": 2000, "penjara": 20},
    "1T": {"nama": "Heavy Truck in City", "deskripsi": "Truk besar masuk kota", "denda": 3000, "penjara": 0},
    "1U": {"nama": "Drugs in Trunk", "deskripsi": "Narkoba di bagasi", "denda": 5000, "penjara": 0},
    "1V": {"nama": "Marijuana in Trunk", "deskripsi": "Ganja di bagasi", "denda": 4000, "penjara": 0},
    "1W": {"nama": "Gun Materials in Trunk", "deskripsi": "Bahan senjata di bagasi", "denda": 5000, "penjara": 0},
    "1X": {"nama": "Gun Bullets in Trunk", "deskripsi": "Peluru di bagasi", "denda": 5000, "penjara": 0},
    "1Y-1": {"nama": "Weapon in Trunk (1 slot)", "deskripsi": "1 senjata di bagasi", "denda": 5000, "penjara": 0},
    "1Y-2": {"nama": "Weapon in Trunk (2 slots)", "deskripsi": "2 senjata di bagasi", "denda": 6000, "penjara": 0},
    "1Y-3": {"nama": "Weapon in Trunk (3 slots)", "deskripsi": "3 senjata di bagasi", "denda": 7000, "penjara": 0},
    "1Y-4": {"nama": "Weapon in Trunk (4 slots)", "deskripsi": "4 senjata di bagasi", "denda": 8000, "penjara": 0},
    "1Y-5": {"nama": "Weapon in Trunk (5 slots)", "deskripsi": "5 senjata di bagasi", "denda": 9000, "penjara": 0},
    "1Z": {"nama": "Inappropriate Stickers", "deskripsi": "Stiker tidak pantas", "denda": 2000, "penjara": 20},
    "2D": {"nama": "Illegal Lumberjack", "deskripsi": "Penebangan liar", "denda": 2000, "penjara": 15},
    "2E": {"nama": "Illegal Fishing", "deskripsi": "Penangkapan ikan ilegal", "denda": 2000, "penjara": 15},
    "2F": {"nama": "Small Illegal Event", "deskripsi": "Acara kecil ilegal", "denda": 5000, "penjara": 15},
    "2G": {"nama": "Big Illegal Event", "deskripsi": "Acara besar ilegal", "denda": 7000, "penjara": 25},
    "3A": {"nama": "Drug Possession (Small)", "deskripsi": "Narkoba 1-50 gram", "denda": 2000, "penjara": 20},
    "3B": {"nama": "Drug Possession (Large)", "deskripsi": "Narkoba 51-100 gram", "denda": 3000, "penjara": 30},
    "3C": {"nama": "IUI or IWI", "deskripsi": "Di bawah pengaruh narkoba", "denda": 2000, "penjara": 30},
    "3D": {"nama": "Selling/Distributing Drugs", "deskripsi": "Menjual/distribusi narkoba", "denda": 4000, "penjara": 30},
    "3E": {"nama": "Drug Manufacturing", "deskripsi": "Memproduksi narkoba", "denda": 5000, "penjara": 40},
    "3F": {"nama": "Present for Drug Use", "deskripsi": "Hadir di pesta narkoba", "denda": 2000, "penjara": 20},
    "3G": {"nama": "Drug Smuggler", "deskripsi": "Menyelundupkan narkoba", "denda": 5000, "penjara": 30},
    "3H": {"nama": "Drug Dealer", "deskripsi": "Dealer narkoba", "denda": 6000, "penjara": 40},
    "4A": {"nama": "Intimidation", "deskripsi": "Intimidasi/mengancam", "denda": 2000, "penjara": 10},
    "4B": {"nama": "Assault", "deskripsi": "Penyerangan", "denda": 2000, "penjara": 15},
    "4C": {"nama": "Assault with Deadly Weapons", "deskripsi": "Penyerangan dengan senjata", "denda": 4000, "penjara": 30},
    "4D": {"nama": "Battery", "deskripsi": "Kontak fisik tanpa izin", "denda": 2000, "penjara": 20},
    "4E": {"nama": "Aggravated Battery", "deskripsi": "Kontak fisik berbahaya", "denda": 3000, "penjara": 25},
    "4F": {"nama": "Attempted Murder", "deskripsi": "Percobaan pembunuhan", "denda": 5000, "penjara": 25},
    "4G": {"nama": "Murder", "deskripsi": "Pembunuhan", "denda": 6000, "penjara": 30},
    "4H": {"nama": "Group Criminal Assault", "deskripsi": "Penyerangan berkelompok", "denda": 5000, "penjara": 30},
    "4I": {"nama": "Drive-By Shooting", "deskripsi": "Penembakan dari kendaraan", "denda": 5000, "penjara": 25},
    "4J": {"nama": "Melee Robbery", "deskripsi": "Perampokan dengan kekerasan", "denda": 5000, "penjara": 30},
    "4K": {"nama": "Armed Robbery", "deskripsi": "Perampokan bersenjata", "denda": 7000, "penjara": 40},
    "4L": {"nama": "Piracy", "deskripsi": "Pembajakan kapal", "denda": 3000, "penjara": 20},
    "4M": {"nama": "Grand Theft", "deskripsi": "Pencurian properti >$1,000", "denda": 4000, "penjara": 30},
    "4N": {"nama": "Grand Theft Auto", "deskripsi": "Pencurian kendaraan", "denda": 3000, "penjara": 25},
    "4O": {"nama": "Grand Theft of Firearms", "deskripsi": "Pencurian senjata", "denda": 5000, "penjara": 30},
    "4P": {"nama": "Abuse of Dead Body", "deskripsi": "Pelecehan mayat", "denda": 4000, "penjara": 30},
    "4Q": {"nama": "Kidnapping", "deskripsi": "Penculikan", "denda": 7000, "penjara": 50},
    "4R": {"nama": "Hostage Taking", "deskripsi": "Penyanderaan", "denda": 10000, "penjara": 60},
    "4S": {"nama": "Torture", "deskripsi": "Penyiksaan", "denda": 8000, "penjara": 40},
    "4T": {"nama": "Blackmail", "deskripsi": "Pemerasan", "denda": 3000, "penjara": 20},
    "4U": {"nama": "Human Trafficking", "deskripsi": "Perdagangan manusia", "denda": 10000, "penjara": 60},
    "4V": {"nama": "Sexual Harassment", "deskripsi": "Pelecehan seksual", "denda": 3000, "penjara": 20},
    "4W": {"nama": "Rape", "deskripsi": "Pemerkosaan", "denda": 5000, "penjara": 30},
    "4X": {"nama": "Prostitution", "deskripsi": "Prostitusi", "denda": 4000, "penjara": 25},
    "4Y": {"nama": "Rob ATM & Mart", "deskripsi": "Merampok ATM/Mart", "denda": 15000, "penjara": 50},
    "4Z": {"nama": "Rob Bank", "deskripsi": "Merampok Bank", "denda": 20000, "penjara": 60},
    "5A": {"nama": "Sharp/Blunt Weapons", "deskripsi": "Senjata tajam/tumpul", "denda": 2000, "penjara": 20},
    "5B": {"nama": "Illegal Firearms", "deskripsi": "Senjata tanpa nomor seri", "denda": 4000, "penjara": 20},
    "5C": {"nama": "Firearms Without License", "deskripsi": "Senjata tanpa lisensi", "denda": 3000, "penjara": 25},
    "5D": {"nama": "Weapon Materials", "deskripsi": "Bahan pembuatan senjata", "denda": 3000, "penjara": 20},
    "5F": {"nama": "Brandishing Firearm", "deskripsi": "Mengacungkan senjata", "denda": 4000, "penjara": 25},
    "5G": {"nama": "Unlawful Discharge", "deskripsi": "Menembak sembarangan", "denda": 2000, "penjara": 20},
    "5H": {"nama": "Body Armor", "deskripsi": "Pelindung tubuh", "denda": 2000, "penjara": 10},
    "5I": {"nama": "Weapon Trafficking", "deskripsi": "Penyelundupan senjata", "denda": 5000, "penjara": 30},
    "5J": {"nama": "Arms Dealer", "deskripsi": "Dealer senjata", "denda": 6000, "penjara": 35},
    "5K": {"nama": "Firearms Manufacturing", "deskripsi": "Pembuatan senjata ilegal", "denda": 7000, "penjara": 40},
    "5L": {"nama": "Arms Smuggler", "deskripsi": "Penyelundup senjata", "denda": 5000, "penjara": 30},
    "6A": {"nama": "Initiating Riot", "deskripsi": "Memulai kerusuhan", "denda": 2500, "penjara": 25},
    "6B": {"nama": "Failing to Disperse", "deskripsi": "Menolak bubar", "denda": 1500, "penjara": 10},
    "6C": {"nama": "Participating in Riot", "deskripsi": "Ikut kerusuhan", "denda": 2000, "penjara": 20},
    "6D": {"nama": "Spitting in Public", "deskripsi": "Meludah di publik", "denda": 1000, "penjara": 0},
    "6E": {"nama": "Pee in Public", "deskripsi": "BAK di publik", "denda": 1000, "penjara": 0},
    "6F": {"nama": "Drunk in Public", "deskripsi": "Mabuk di publik", "denda": 1000, "penjara": 0},
    "6G": {"nama": "Vilification", "deskripsi": "Memfitnah", "denda": 2000, "penjara": 20},
    "6H": {"nama": "Hate Speech", "deskripsi": "Ujaran kebencian", "denda": 2500, "penjara": 20},
    "6I": {"nama": "Vigilantism", "deskripsi": "Main hakim sendiri", "denda": 3000, "penjara": 30},
    "6J": {"nama": "Disturbing Peace", "deskripsi": "Mengganggu ketenangan", "denda": 2000, "penjara": 20},
    "6K": {"nama": "Brawl in Public", "deskripsi": "Tawuran di publik", "denda": 4000, "penjara": 30},
    "6L": {"nama": "Accessories Disturbance", "deskripsi": "Aksesoris mengganggu", "denda": 1000, "penjara": 0},
    "6M": {"nama": "Jaywalk", "deskripsi": "Menyeberang sembarangan", "denda": 1000, "penjara": 0},
    "6N": {"nama": "Littering", "deskripsi": "Buang sampah sembarangan", "denda": 1500, "penjara": 0},
    "6O": {"nama": "Unlawful Assembly", "deskripsi": "Berkumpul melawan hukum", "denda": 1500, "penjara": 20},
    "6P": {"nama": "Stalking", "deskripsi": "Menguntit", "denda": 2000, "penjara": 20},
    "6Q": {"nama": "Public Intoxication", "deskripsi": "Mabuk mengganggu", "denda": 1500, "penjara": 10},
    "6R": {"nama": "Animal Abuse", "deskripsi": "Menyakiti hewan", "denda": 1500, "penjara": 20},
    "6S": {"nama": "Animal Cruelty", "deskripsi": "Kekejaman terhadap hewan", "denda": 1500, "penjara": 0},
    "6T": {"nama": "Slander", "deskripsi": "Fitnah", "denda": 1500, "penjara": 20},
    "6U": {"nama": "Naked in Public", "deskripsi": "Telanjang di publik", "denda": 2500, "penjara": 15},
    "6V": {"nama": "Sexual Action in Public", "deskripsi": "Seks di publik", "denda": 3000, "penjara": 25},
    "7A": {"nama": "Obstruction of Justice", "deskripsi": "Menghalangi petugas", "denda": 2500, "penjara": 20},
    "7B": {"nama": "Abusing Hotline", "deskripsi": "Penyalahgunaan 911", "denda": 2000, "penjara": 10},
    "7C": {"nama": "Government Attribute", "deskripsi": "Atribut pemerintah", "denda": 1500, "penjara": 20},
    "7D": {"nama": "Impersonating Gov Staff", "deskripsi": "Menyamar jadi petugas", "denda": 5000, "penjara": 30},
    "7E": {"nama": "Bribery", "deskripsi": "Menyuap petugas", "denda": 5000, "penjara": 35},
    "7F": {"nama": "Bribing Witnesses", "deskripsi": "Menyuap saksi", "denda": 2500, "penjara": 20},
    "7G": {"nama": "False Report", "deskripsi": "Laporan palsu", "denda": 3000, "penjara": 20},
    "7H": {"nama": "False Info to Police", "deskripsi": "Info palsu ke polisi", "denda": 2000, "penjara": 10},
    "7I": {"nama": "Perjury", "deskripsi": "Bohong di bawah sumpah", "denda": 2500, "penjara": 30},
    "7J": {"nama": "Assaulting LEO", "deskripsi": "Menyerang petugas", "denda": 5000, "penjara": 30},
    "7K": {"nama": "Attempted Murder Official", "deskripsi": "Coba bunuh pejabat", "denda": 8000, "penjara": 40},
    "7L": {"nama": "Murder Official", "deskripsi": "Bunuh pejabat", "denda": 10000, "penjara": 50},
    "7M": {"nama": "Harbouring Criminals", "deskripsi": "Sembunyikan penjahat", "denda": 10000, "penjara": 30},
    "7N": {"nama": "Fraud/Scam", "deskripsi": "Penipuan", "denda": 5000, "penjara": 30},
    "7O": {"nama": "Forgery", "deskripsi": "Pemalsuan dokumen", "denda": 4000, "penjara": 20},
    "7P": {"nama": "Corruption", "deskripsi": "Korupsi", "denda": 20000, "penjara": 90},
    "8A": {"nama": "Trespassing", "deskripsi": "Masuk properti tanpa izin", "denda": 3000, "penjara": 20},
    "8B": {"nama": "Trespassing Gov Property", "deskripsi": "Masuk gedung pemerintah", "denda": 2000, "penjara": 15},
    "8C": {"nama": "Vandalism", "deskripsi": "Merusak properti", "denda": 3000, "penjara": 30},
    "8D": {"nama": "Arson", "deskripsi": "Membakar properti", "denda": 3500, "penjara": 30},
    "8E": {"nama": "Extortion", "deskripsi": "Pemerasan dengan kekerasan", "denda": 3000, "penjara": 35},
    "8F": {"nama": "Property as Illegal Distro", "deskripsi": "Properti distribusi ilegal", "denda": 6000, "penjara": 40},
    "8G": {"nama": "Burglary", "deskripsi": "Merampok properti", "denda": 7000, "penjara": 50},
    "9A": {"nama": "Brawl Against Inmate", "deskripsi": "Tawuran di penjara", "denda": 0, "penjara": 20},
    "9B": {"nama": "Jailbreak", "deskripsi": "Kabur dari penjara", "denda": 0, "penjara": 40},
    "9C": {"nama": "Inciting Riot in Prison", "deskripsi": "Hasut kerusuhan penjara", "denda": 0, "penjara": 20}
}

window.PENAL_CATEGORIES = {
  '1': 'Traffic and vehicle',
  '2': 'Licenses and permits',
  '3': 'Drug offenses',
  '4': 'Violent crimes',
  '5': 'Weapons offenses',
  '6': 'Public order',
  '7': 'Government crimes',
  '8': 'Property crimes',
  '9': 'Prison offenses'
};

window.PENAL_PRESETS = [
  { id: 'armed_robbery', name: 'Armed robbery', desc: 'Armed robbery suspect', codes: ['1M', '4K', '5B', '7J'] },
  { id: 'smuggler', name: 'Smuggler', desc: 'Drug smuggling suspect', codes: ['1M', '3A', '3G', '5D'] },
  { id: 'vehicle_theft', name: 'Vehicle theft', desc: 'Vehicle theft suspect', codes: ['1M', '4N', '5D'] }
];
